### ISSUE TITLE
RecyclerView的每个Item的点击事件怎么获取

### ISSUE THREAD

**Issue by willBars** [jiang111/IndicatorDialog#3]
博主!您好,看了您写的非常不错的文章,心中有个疑惑?就是RecyclerView的中的每个item的点击事件是怎么获取的,貌似没有看懂?还请指教!

**Comment by jiang111** [comment]
点击事件目前只能在自定义的 adapter 里面进行操作,可以看看 demo 里的自定义 adapter 里面的点击事件
 23行[BaseAdapter.java](https://github.com/jiang111/IndicatorDialog/blob/master/app/src/main/java/com/jiang/android/indicatordialogdemo/BaseAdapter.java)
