### ISSUE TITLE
adapter中的点击事件中获取的id总是一样?是否有误

### ISSUE THREAD

**Issue by willBars** [jiang111/IndicatorDialog#4]
博主你好!
  当项目运行起来的时候,点击dialog中的不同的item的时候,通过v.getId()是不会变的,是否有误?
 public void onItemClick(View v, int position) {
        Toast.makeText(mContext,"点击了"+position+"=="+v.getId(),Toast.LENGTH_SHORT).show();
    }
详见上面的弹出的toast!

**Comment by jiang111** [comment]
id不用管，看 position 就行，onItemClick里的 view 指的就是 recyclerview 的 item 的根布局，id 肯定是一样的，要不然怎么复用呢
