### ISSUE TITLE
点击条目之后无法关闭dialog。

### ISSUE THREAD

**Issue by EpicWang** [jiang111/IndicatorDialog#6]

**Comment by jiang111** [comment]
什么意思，具体一点

**Comment by EpicWang** [comment]
`
final IndicatorDialog dialog = new IndicatorBuilder(this)
                .width(500)
                .height((int) (height * 0.3))
                .ArrowDirection(IndicatorBuilder.TOP)
                .bgColor(Color.WHITE)
                .gravity(IndicatorBuilder.GRAVITY_RIGHT)
                .ArrowRectage(0.9f)
                .radius(18)
                .layoutManager(new LinearLayoutManager(this, LinearLayoutManager.VERTICAL, false))
                .adapter(new BaseAdapter() {
                       @Override
                       public void onItemClick(View v, int position) {
                               //这里点击了条目之后，需要调用dialog.dismiss()关闭，但是提示dialog没有初始化
                       }
                }
                .create();
`

**Comment by jiang111** [comment]
是v1.3.8的版本吗，我这里没问题

**Comment by EpicWang** [comment]
是的，用的是这个版本
`compile 'com.github.jiang111:IndicatorDialog:v1.3.8'`
我想的是，在create()方法才是创建dialog，adapter()方法是在create()方法之前调用的，所以这个提示也没错，那有没有其他方式，在点击了条目之后关闭dialog

**Comment by jiang111** [comment]
这是我的demo 是没问题的，看看是不是某个地方写的不对
![qq20171222-162024](https://user-images.githubusercontent.com/3346368/34290760-1fee4124-e734-11e7-9b03-cedb8f52a891.png)

**Comment by EpicWang** [comment]
多谢耐心回答，我这里没有单独声明dialog，所以在adapter()中IDE检测到dialog还没初始化
`final IndicatorDialog dialog = new IndicatorBuilder(this).create()`

再次感谢！
